language: node_js
node_js:
- 9.3.0
after_script:
- scp -r -o StrictHostKeyChecking=no ./test 139.199.72.81:/root/zq/test

before_install:
- openssl aes-256-cbc -K $encrypted_356163df3357_key -iv $encrypted_356163df3357_iv
  -in zq_key.enc -out ~\/.ssh/zq_key -d

- chmod 600 ~/.ssh/zq_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/zq_key
- cp .travis/ssh_config ~/.ssh/config
- chmod 600 ~/.ssh/config